# Use an official Python runtime as a parent image

FROM python:3.9-slim
 
# Set the working directory in the container

WORKDIR /app
 
# Copy the current directory contents into the container at /app

COPY . .
 


#  install any needed packages specified in requirements.txt Copy requirements.txt

RUN pip install --no-cache-dir -r requirements.txt



 
# Make port 5000 available to the world outside this container

EXPOSE 5000
 
# Define environment variable

ENV FLASK_APP=northwind_web.py
 
# Run app.py when the container launches

CMD [ "waitress-serve", "--port=5000", "northwind_web:app"]


# NOTES FOR MYSELF
# docker images -a
# to build "docker build --tag northwind_app ."

# docker build --tag northwind_app .

# docker run -p 5000:5000 northwind_app
# INFO:waitress:Serving on http://0.0.0.0:5000
