# select type of API version and type of service/object
apiVersion: v1
kind: Service

# metadata for name
metadata: 
  name: nginx-svc
  namespace: default

# specification to include port slector to connect to the deployment.
spec:
  ports:
  - nodePort: 30001  # range is 30001-32768
    port: 80
    targetPort: 80

  # selector
  selector:
    app: nginx

  type: NodePort  # always use load balancer for local ip cluster