# where do you want to install or run this playbook?
- hosts: web
 
  # would you like to see the logs?
  gather_facts: yes
 
  # provide admin access to this playbook - use sudo
  become: true
 
  # instructions - tasks install nodejs in agent node
  tasks:
    - name: install nodejs and npm on the agent node
      apt: 
        pkg: 
          - nodejs
          - npm
 
    - name: clone repo
      git: 
        repo: https://github.com/Scarlett100/ci_cd_again.git
        dest: /home/ubuntu/ci_cd_again
        clone: yes
        update: yes
 
    - name: change directory to app
      shell: cd /home/ubuntu/ci_cd_again/app

    - name: Install pm2
      npm:
       name: pm2
       global: yes

    - name: Start app
      shell: |
        cd /app
        npm install
        pm2 kill
        pm2 start app.js

      
                                          
        